"""Add prompt_content

Revision ID: bf2c4d618240
Revises: 
Create Date: 2025-11-19 14:49:04.500686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf2c4d618240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('prompt_content', sa.Text(), nullable=True, comment='Full prompt sent to LLM'))
    op.alter_column('agent_decisions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='success, failed, or parsing_error',
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('agent_decisions', 'action',
               existing_type=sa.VARCHAR(length=20),
               comment='OPEN_LONG, OPEN_SHORT, CLOSE_POSITION, or HOLD',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'coin',
               existing_type=sa.VARCHAR(length=10),
               comment='BTC, ETH, SOL, BNB, DOGE, or XRP',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'size_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='Position size in USD (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'leverage',
               existing_type=sa.INTEGER(),
               comment='Leverage 1-50x (1 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'stop_loss_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='Stop loss price (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'take_profit_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='Take profit price (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='Confidence score 0.00-1.00',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'reasoning',
               existing_type=sa.TEXT(),
               comment="LLM's reasoning for the decision",
               existing_nullable=False)
    op.alter_column('agent_decisions', 'llm_response',
               existing_type=sa.TEXT(),
               comment='Raw response from LLM',
               existing_nullable=True)
    op.alter_column('agent_decisions', 'execution_time_ms',
               existing_type=sa.INTEGER(),
               comment='Time taken for LLM call in milliseconds',
               existing_nullable=True)
    op.alter_column('agent_decisions', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if status=failed',
               existing_nullable=True)
    op.drop_index('idx_agent_decisions_action', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_agent_id', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_coin', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_status', table_name='agent_decisions')
    op.drop_index('idx_agent_decisions_timestamp', table_name='agent_decisions')
    op.create_index(op.f('ix_agent_decisions_action'), 'agent_decisions', ['action'], unique=False)
    op.create_index(op.f('ix_agent_decisions_agent_id'), 'agent_decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_coin'), 'agent_decisions', ['coin'], unique=False)
    op.create_index(op.f('ix_agent_decisions_status'), 'agent_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_decisions_timestamp'), 'agent_decisions', ['timestamp'], unique=False)
    op.drop_constraint('agent_decisions_agent_id_fkey', 'agent_decisions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_decisions', 'trading_agents', ['agent_id'], ['id'])
    op.alter_column('agent_performance', 'num_trades',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_performance', 'num_winning_trades',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_performance', 'num_losing_trades',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_agent_performance_agent_id', table_name='agent_performance')
    op.drop_index('idx_agent_performance_snapshot_time', table_name='agent_performance')
    op.create_index(op.f('ix_agent_performance_agent_id'), 'agent_performance', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_performance_snapshot_time'), 'agent_performance', ['snapshot_time'], unique=False)
    op.drop_constraint('agent_performance_agent_id_fkey', 'agent_performance', type_='foreignkey')
    op.create_foreign_key(None, 'agent_performance', 'trading_agents', ['agent_id'], ['id'])
    op.drop_index('idx_agent_trades_agent_id', table_name='agent_trades')
    op.drop_index('idx_agent_trades_coin', table_name='agent_trades')
    op.drop_index('idx_agent_trades_entry_time', table_name='agent_trades')
    op.drop_index('idx_agent_trades_status', table_name='agent_trades')
    op.create_index(op.f('ix_agent_trades_agent_id'), 'agent_trades', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_trades_coin'), 'agent_trades', ['coin'], unique=False)
    op.create_index(op.f('ix_agent_trades_entry_time'), 'agent_trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_agent_trades_status'), 'agent_trades', ['status'], unique=False)
    op.drop_constraint('agent_trades_agent_id_fkey', 'agent_trades', type_='foreignkey')
    op.drop_constraint('agent_trades_decision_id_fkey', 'agent_trades', type_='foreignkey')
    op.create_foreign_key(None, 'agent_trades', 'agent_decisions', ['decision_id'], ['id'])
    op.create_foreign_key(None, 'agent_trades', 'trading_agents', ['agent_id'], ['id'])
    op.alter_column('bot_state', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment="State key (e.g., 'trading_bot_state')",
               existing_nullable=False)
    op.alter_column('bot_state', 'value',
               existing_type=sa.TEXT(),
               comment='Serialized state (JSON string)',
               existing_nullable=False)
    op.alter_column('bot_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trading_agents', 'llm_model',
               existing_type=sa.VARCHAR(length=50),
               comment='References model name in config.llm.models',
               existing_nullable=False)
    op.alter_column('trading_agents', 'exchange_account',
               existing_type=sa.VARCHAR(length=50),
               comment='References account name in config.exchange.accounts',
               existing_nullable=False)
    op.alter_column('trading_agents', 'max_position_size',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Max position size as % of account value',
               existing_nullable=False,
               existing_server_default=sa.text('20.0'))
    op.alter_column('trading_agents', 'max_leverage',
               existing_type=sa.INTEGER(),
               comment='Maximum allowed leverage (1-50x)',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('trading_agents', 'stop_loss_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Stop loss percentage',
               existing_nullable=False,
               existing_server_default=sa.text('2.0'))
    op.alter_column('trading_agents', 'take_profit_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Take profit percentage',
               existing_nullable=False,
               existing_server_default=sa.text('5.0'))
    op.alter_column('trading_agents', 'strategy_description',
               existing_type=sa.TEXT(),
               comment='Description of trading strategy for this agent',
               existing_nullable=True)
    op.drop_index('idx_trading_agents_llm_model', table_name='trading_agents')
    op.drop_index('idx_trading_agents_status', table_name='trading_agents')
    op.create_index(op.f('ix_trading_agents_llm_model'), 'trading_agents', ['llm_model'], unique=False)
    op.create_index(op.f('ix_trading_agents_status'), 'trading_agents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_agents_status'), table_name='trading_agents')
    op.drop_index(op.f('ix_trading_agents_llm_model'), table_name='trading_agents')
    op.create_index('idx_trading_agents_status', 'trading_agents', ['status'], unique=False)
    op.create_index('idx_trading_agents_llm_model', 'trading_agents', ['llm_model'], unique=False)
    op.alter_column('trading_agents', 'strategy_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description of trading strategy for this agent',
               existing_nullable=True)
    op.alter_column('trading_agents', 'take_profit_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Take profit percentage',
               existing_nullable=False,
               existing_server_default=sa.text('5.0'))
    op.alter_column('trading_agents', 'stop_loss_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Stop loss percentage',
               existing_nullable=False,
               existing_server_default=sa.text('2.0'))
    op.alter_column('trading_agents', 'max_leverage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum allowed leverage (1-50x)',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('trading_agents', 'max_position_size',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Max position size as % of account value',
               existing_nullable=False,
               existing_server_default=sa.text('20.0'))
    op.alter_column('trading_agents', 'exchange_account',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='References account name in config.exchange.accounts',
               existing_nullable=False)
    op.alter_column('trading_agents', 'llm_model',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='References model name in config.llm.models',
               existing_nullable=False)
    op.alter_column('bot_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_state', 'value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Serialized state (JSON string)',
               existing_nullable=False)
    op.alter_column('bot_state', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="State key (e.g., 'trading_bot_state')",
               existing_nullable=False)
    op.drop_constraint(None, 'agent_trades', type_='foreignkey')
    op.drop_constraint(None, 'agent_trades', type_='foreignkey')
    op.create_foreign_key('agent_trades_decision_id_fkey', 'agent_trades', 'agent_decisions', ['decision_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('agent_trades_agent_id_fkey', 'agent_trades', 'trading_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_trades_status'), table_name='agent_trades')
    op.drop_index(op.f('ix_agent_trades_entry_time'), table_name='agent_trades')
    op.drop_index(op.f('ix_agent_trades_coin'), table_name='agent_trades')
    op.drop_index(op.f('ix_agent_trades_agent_id'), table_name='agent_trades')
    op.create_index('idx_agent_trades_status', 'agent_trades', ['status'], unique=False)
    op.create_index('idx_agent_trades_entry_time', 'agent_trades', ['entry_time'], unique=False)
    op.create_index('idx_agent_trades_coin', 'agent_trades', ['coin'], unique=False)
    op.create_index('idx_agent_trades_agent_id', 'agent_trades', ['agent_id'], unique=False)
    op.drop_constraint(None, 'agent_performance', type_='foreignkey')
    op.create_foreign_key('agent_performance_agent_id_fkey', 'agent_performance', 'trading_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_performance_snapshot_time'), table_name='agent_performance')
    op.drop_index(op.f('ix_agent_performance_agent_id'), table_name='agent_performance')
    op.create_index('idx_agent_performance_snapshot_time', 'agent_performance', ['snapshot_time'], unique=False)
    op.create_index('idx_agent_performance_agent_id', 'agent_performance', ['agent_id'], unique=False)
    op.alter_column('agent_performance', 'num_losing_trades',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_performance', 'num_winning_trades',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_performance', 'num_trades',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'agent_decisions', type_='foreignkey')
    op.create_foreign_key('agent_decisions_agent_id_fkey', 'agent_decisions', 'trading_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_decisions_timestamp'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_status'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_coin'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_agent_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_action'), table_name='agent_decisions')
    op.create_index('idx_agent_decisions_timestamp', 'agent_decisions', ['timestamp'], unique=False)
    op.create_index('idx_agent_decisions_status', 'agent_decisions', ['status'], unique=False)
    op.create_index('idx_agent_decisions_coin', 'agent_decisions', ['coin'], unique=False)
    op.create_index('idx_agent_decisions_agent_id', 'agent_decisions', ['agent_id'], unique=False)
    op.create_index('idx_agent_decisions_action', 'agent_decisions', ['action'], unique=False)
    op.alter_column('agent_decisions', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if status=failed',
               existing_nullable=True)
    op.alter_column('agent_decisions', 'execution_time_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Time taken for LLM call in milliseconds',
               existing_nullable=True)
    op.alter_column('agent_decisions', 'llm_response',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw response from LLM',
               existing_nullable=True)
    op.alter_column('agent_decisions', 'reasoning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="LLM's reasoning for the decision",
               existing_nullable=False)
    op.alter_column('agent_decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='Confidence score 0.00-1.00',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'take_profit_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment=None,
               existing_comment='Take profit price (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'stop_loss_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment=None,
               existing_comment='Stop loss price (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'leverage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Leverage 1-50x (1 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'size_usd',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment=None,
               existing_comment='Position size in USD (0 for HOLD/CLOSE)',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'coin',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='BTC, ETH, SOL, BNB, DOGE, or XRP',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'action',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='OPEN_LONG, OPEN_SHORT, CLOSE_POSITION, or HOLD',
               existing_nullable=False)
    op.alter_column('agent_decisions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='success, failed, or parsing_error',
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_column('agent_decisions', 'prompt_content')
    # ### end Alembic commands ###
