"""add security_events table

Revision ID: 08892484eb4c
Revises: 4df4faa0d893
Create Date: 2025-12-01 00:30:53.445889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08892484eb4c'
down_revision: Union[str, None] = '4df4faa0d893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='injection_attempt, pii_leakage, etc.'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='low, medium, high, critical'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the event'),
    sa.Column('original_content', sa.Text(), nullable=True, comment='Original content that triggered the event (if safe to store)'),
    sa.Column('agent_id', sa.UUID(), nullable=True, comment='Agent ID associated with the event (if any)'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.ForeignKeyConstraint(['agent_id'], ['trading_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
