"""add_chain_of_thought

Revision ID: 4df4faa0d893
Revises: bf2c4d618240
Create Date: 2025-11-20 21:23:42.305513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4df4faa0d893'
down_revision: Union[str, None] = 'bf2c4d618240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('chain_of_thought', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured Chain of Thought JSON'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decisions', 'chain_of_thought')
    # ### end Alembic commands ###
